######################################################################
# Automatically generated by qmake (2.01a) mi� nov 26 15:21:39 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += calificacion.h \
           estudiante.h \
           materia.h \
           pInicial.h \
           pPrincipal.h \
           semestre.h \
    modelosemestre.h
FORMS += inicial.ui principal.ui
SOURCES += calificacion.cpp \
           estudiante.cpp \
           main.cpp \
           materia.cpp \
           pInicial.cpp \
           pPrincipal.cpp \
           semestre.cpp \
    modelosemestre.cpp
